import { IExercise, MuscleGroup } from '@/app/types/types';

export const exercises: IExercise[] = [
  {
    id: 1,
    name: 'Отжимания',
    description: 'Отжимания отлично прорабатывают грудь, плечи и трицепсы.',
    muscleGroup: MuscleGroup.CHEST,
  },
  {
    id: 2,
    name: 'Подтягивания',
    description: 'Подтягивания эффективно тренируют спину, плечи и бицепсы.',
    muscleGroup: MuscleGroup.BACK,
  },
  {
    id: 3,
    name: 'Приседания',
    description: 'Приседания отлично прорабатывают ноги, ягодицы и корпус.',
    muscleGroup: MuscleGroup.LEGS,
  },
  {
    id: 4,
    name: 'Жим лежа',
    description: 'Жим лежа эффективно тренирует грудь, плечи и трицепсы.',
    muscleGroup: MuscleGroup.CHEST,
  },
  {
    id: 5,
    name: 'Становая тяга',
    description: 'Становая тяга отлично прорабатывает спину, плечи и бицепсы.',
    muscleGroup: MuscleGroup.BACK,
  },
  {
    id: 6,
    name: 'Жим гантелей сидя',
    description: 'Жим гантелей сидя прорабатывает дельтовидные мышцы и трицепсы.',
    muscleGroup: MuscleGroup.SHOULDERS,
  },
  {
    id: 7,
    name: 'Подъемы на бицепс',
    description: 'Подъемы на бицепс изолированно тренируют бицепсы.',
    muscleGroup: MuscleGroup.BICEPS,
  },
  {
    id: 8,
    name: 'Отжимания на брусьях',
    description: 'Отжимания на брусьях эффективно прорабатывают трицепсы и грудь.',
    muscleGroup: MuscleGroup.TRICEPS,
  },
  {
    id: 9,
    name: 'Выпады',
    description: 'Выпады прорабатывают квадрицепсы, бицепсы бедра и ягодицы.',
    muscleGroup: MuscleGroup.LEGS,
  },
  {
    id: 10,
    name: 'Планка',
    description: 'Планка отлично укрепляет мышцы корпуса.',
    muscleGroup: MuscleGroup.CORE,
  },
  {
    id: 11,
    name: 'Русские скручивания',
    description: 'Русские скручивания прорабатывают косые мышцы живота.',
    muscleGroup: MuscleGroup.CORE,
  },
  {
    id: 12,
    name: 'Тяга верхнего блока',
    description: 'Тяга верхнего блока прорабатывает широчайшие мышцы спины и бицепсы.',
    muscleGroup: MuscleGroup.BACK,
  },
  {
    id: 13,
    name: 'Подъемы на носки',
    description: 'Подъемы на носки укрепляют икроножные и камбаловидные мышцы.',
    muscleGroup: MuscleGroup.LEGS,
  },
  {
    id: 14,
    name: 'Разведение рук в стороны',
    description: 'Разведение рук в стороны прорабатывает средние дельты.',
    muscleGroup: MuscleGroup.SHOULDERS,
  },
  {
    id: 15,
    name: 'Молотковые сгибания',
    description: 'Молотковые сгибания прорабатывают бицепсы и предплечья.',
    muscleGroup: MuscleGroup.BICEPS,
  },
  {
    id: 16,
    name: 'Жим гантелей на наклонной скамье',
    description: 'Прорабатывает верхнюю часть груди и плечи.',
    muscleGroup: MuscleGroup.CHEST,
  },
  {
    id: 17,
    name: 'Отжимания с ногами на возвышении',
    description: 'Акцент на нижнюю часть груди.',
    muscleGroup: MuscleGroup.CHEST,
  },
  {
    id: 18,
    name: 'Сведение рук в кроссовере',
    description: 'Изолированная проработка грудных мышц.',
    muscleGroup: MuscleGroup.CHEST,
  },
  {
    id: 19,
    name: 'Тяга в наклоне',
    description: 'Укрепляет верхнюю часть спины и бицепсы.',
    muscleGroup: MuscleGroup.BACK,
  },
  {
    id: 20,
    name: 'Тяга Т-грифа',
    description: 'Отлично развивает среднюю часть спины.',
    muscleGroup: MuscleGroup.BACK,
  },
  {
    id: 21,
    name: 'Тяга к лицу',
    description: 'Прорабатывает задние дельты и верх спины.',
    muscleGroup: MuscleGroup.BACK,
  },
  {
    id: 22,
    name: 'Жим Арнольда',
    description: 'Комплексное упражнение для развития плеч.',
    muscleGroup: MuscleGroup.SHOULDERS,
  },
  {
    id: 23,
    name: 'Подъемы рук перед собой',
    description: 'Изолированная проработка передних дельт.',
    muscleGroup: MuscleGroup.SHOULDERS,
  },
  {
    id: 24,
    name: 'Разведение рук в наклоне',
    description: 'Прорабатывает задние дельты и верх спины.',
    muscleGroup: MuscleGroup.SHOULDERS,
  },
  {
    id: 25,
    name: 'Концентрированные сгибания',
    description: 'Изолированная проработка бицепсов.',
    muscleGroup: MuscleGroup.BICEPS,
  },
  {
    id: 26,
    name: 'Сгибания рук на скамье Скотта',
    description: 'Изолированная проработка бицепсов.',
    muscleGroup: MuscleGroup.BICEPS,
  },
  {
    id: 27,
    name: 'Сгибания Зоттмана',
    description: 'Прорабатывает бицепсы и предплечья.',
    muscleGroup: MuscleGroup.BICEPS,
  },
  {
    id: 28,
    name: 'Французский жим',
    description: 'Отличное изолирующее упражнение для трицепсов.',
    muscleGroup: MuscleGroup.TRICEPS,
  },
  {
    id: 29,
    name: 'Разгибание рук из-за головы',
    description: 'Прорабатывает длинную головку трицепса.',
    muscleGroup: MuscleGroup.TRICEPS,
  },
  {
    id: 30,
    name: 'Разгибание рук на блоке',
    description: 'Изолированная проработка трицепсов.',
    muscleGroup: MuscleGroup.TRICEPS,
  },
  {
    id: 31,
    name: 'Жим ногами',
    description: 'Базовое упражнение для квадрицепсов.',
    muscleGroup: MuscleGroup.LEGS,
  },
  {
    id: 32,
    name: 'Румынская становая тяга',
    description: 'Акцент на бицепсы бедра и ягодицы.',
    muscleGroup: MuscleGroup.LEGS,
  },
  {
    id: 33,
    name: 'Болгарские приседания',
    description: 'Одностороннее упражнение для ног.',
    muscleGroup: MuscleGroup.LEGS,
  },
  {
    id: 34,
    name: 'Подъемы ног в висе',
    description: 'Продвинутое упражнение для нижнего пресса.',
    muscleGroup: MuscleGroup.CORE,
  },
  {
    id: 35,
    name: 'Роллаут с колесом',
    description: 'Сложное упражнение для всего пресса.',
    muscleGroup: MuscleGroup.CORE,
  },
  {
    id: 36,
    name: 'Жим гантелей лежа',
    description: 'Альтернатива жиму штанги лежа.',
    muscleGroup: MuscleGroup.CHEST,
  },
  {
    id: 37,
    name: 'Австралийские подтягивания',
    description: 'Упражнение с собственным весом для спины.',
    muscleGroup: MuscleGroup.BACK,
  },
  {
    id: 38,
    name: 'Тяга к подбородку',
    description: 'Прорабатывает плечи и верх трапеций.',
    muscleGroup: MuscleGroup.SHOULDERS,
  },
  {
    id: 39,
    name: 'Сгибания рук на наклонной скамье',
    description: 'Изолированная проработка бицепсов.',
    muscleGroup: MuscleGroup.BICEPS,
  },
  {
    id: 40,
    name: 'Жим лежа узким хватом',
    description: 'Базовое упражнение для трицепсов.',
    muscleGroup: MuscleGroup.TRICEPS,
  },
  {
    id: 41,
    name: 'Зашагивания на платформу',
    description: 'Функциональное упражнение для ног.',
    muscleGroup: MuscleGroup.LEGS,
  },
  {
    id: 42,
    name: 'Подъемы коленей в висе',
    description: 'Упражнение для нижнего пресса.',
    muscleGroup: MuscleGroup.CORE,
  },
  {
    id: 43,
    name: 'Сведение рук в тренажере',
    description: 'Изолированная проработка грудных мышц.',
    muscleGroup: MuscleGroup.CHEST,
  },
  {
    id: 44,
    name: 'Тяга горизонтального блока',
    description: 'Прорабатывает среднюю часть спины.',
    muscleGroup: MuscleGroup.BACK,
  },
  {
    id: 45,
    name: 'Шраги',
    description: 'Прорабатывает трапециевидные мышцы.',
    muscleGroup: MuscleGroup.SHOULDERS,
  },
  {
    id: 46,
    name: 'Обратные сгибания',
    description: 'Прорабатывает бицепсы и предплечья.',
    muscleGroup: MuscleGroup.BICEPS,
  },
  {
    id: 47,
    name: 'Алмазные отжимания',
    description: 'Упражнение с собственным весом для трицепсов.',
    muscleGroup: MuscleGroup.TRICEPS,
  },
  {
    id: 48,
    name: 'Ягодичный мостик',
    description: 'Прорабатывает ягодицы и бицепсы бедра.',
    muscleGroup: MuscleGroup.LEGS,
  },
  {
    id: 49,
    name: 'Боковая планка',
    description: 'Упражнение для косых мышц живота.',
    muscleGroup: MuscleGroup.CORE,
  },
  {
    id: 50,
    name: 'Сведение рук в кроссовере',
    description: 'Изолированная проработка грудных мышц.',
    muscleGroup: MuscleGroup.CHEST,
  },
  {
    id: 51,
    name: 'Тяга гантели одной рукой',
    description: 'Одностороннее упражнение для спины.',
    muscleGroup: MuscleGroup.BACK,
  },
  {
    id: 52,
    name: 'Подъемы блина перед собой',
    description: 'Упражнение для плеч с блином.',
    muscleGroup: MuscleGroup.SHOULDERS,
  },
  {
    id: 53,
    name: 'Сгибания рук с EZ-грифом',
    description: 'Упражнение для бицепсов со специальным грифом.',
    muscleGroup: MuscleGroup.BICEPS,
  },
  {
    id: 54,
    name: 'Разгибание рук с канатом',
    description: 'Упражнение для трицепсов с канатом.',
    muscleGroup: MuscleGroup.TRICEPS,
  },
  {
    id: 55,
    name: 'Выпады в ходьбе',
    description: 'Динамическое упражнение для ног.',
    muscleGroup: MuscleGroup.LEGS,
  },
  {
    id: 56,
    name: 'Скручивания в висе',
    description: 'Продвинутое упражнение для косых мышц.',
    muscleGroup: MuscleGroup.CORE,
  },
  {
    id: 57,
    name: 'Отжимания на брусьях',
    description: 'Базовое упражнение для груди и трицепсов.',
    muscleGroup: MuscleGroup.CHEST,
  },
  {
    id: 58,
    name: 'Подтягивания широким хватом',
    description: 'Продвинутое упражнение для спины.',
    muscleGroup: MuscleGroup.BACK,
  },
  {
    id: 59,
    name: 'Жим из-за головы',
    description: 'Упражнение для плеч со штангой.',
    muscleGroup: MuscleGroup.SHOULDERS,
  },
  {
    id: 60,
    name: 'Сгибания рук на наклонной скамье',
    description: 'Упражнение для бицепсов на наклонной скамье.',
    muscleGroup: MuscleGroup.BICEPS,
  },
  {
    id: 61,
    name: 'Разгибание рук лежа',
    description: 'Упражнение для трицепсов на скамье.',
    muscleGroup: MuscleGroup.TRICEPS,
  },
  {
    id: 62,
    name: 'Прыжки на тумбу',
    description: 'Взрывное упражнение для ног.',
    muscleGroup: MuscleGroup.LEGS,
  },
  {
    id: 63,
    name: 'Скручивания в висе с поворотом',
    description: 'Продвинутое упражнение для корпуса.',
    muscleGroup: MuscleGroup.CORE,
  },
  {
    id: 64,
    name: 'Взрывные отжимания',
    description: 'Взрывное упражнение для груди.',
    muscleGroup: MuscleGroup.CHEST,
  },
  {
    id: 65,
    name: 'Тяга с плинтов',
    description: 'Вариация становой тяги.',
    muscleGroup: MuscleGroup.BACK,
  },
];

const generateFakeExercises = (): IExercise[] => {
  return exercises;
};

export const fetchExercises = async (): Promise<IExercise[]> => {
  return new Promise((resolve) => setTimeout(() => resolve(generateFakeExercises()), 500));
};
